exp:
  out_dir: "runs/exp_pretrain_books"
  seed: 42

include:
  - "configs/model/gpt_small.yaml"
  - "configs/data/books_corpus_open.yaml"

optim:
  lr: 0.00025
  betas: [0.9, 0.95]
  weight_decay: 0.01  # AdamW 风格
  warmup_steps: 2000
  max_steps: 500000
  scheduler: "cosine"
  grad_clip: 1.0
  amp: true

checkpoint:
  save_every: 10000
  keep_last: 5
